name: Auto update outdated PR branches

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  autoupdate:
    name: Auto update PR branches
    runs-on: ubuntu-latest
    steps:
      - name: Auto update open PR branches
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_FILTER: "all"
          PR_READY_STATE: "all"
          MERGE_CONFLICT_ACTION: "ignore"
